version: "2"
services:
  node:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src
      - /usr/app/node_modules
    links:
      - db
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres@db:5432/postgres
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - ".data-postgres:/var/lib/postgresql/data"
    restart: always
