version: "2"
services:
  node:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - db
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://test:test@db:5432/blackford
      - TOKEN_SECRET=<JWT_KEY>
      - CLIENT_SECRET=<CLIENT_SECRET>
      - CLIENT_ID=<CLIENT_ID>
      - FACEBOOK_APP_ID=<FACEBOOK_APP_ID>
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm run docker-dev'
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - .data-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=blackford
    restart: always