version: "2"
services:
  node:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src
      - /usr/app/node_modules
    links:
      - db
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=poop
      - DATABASE_URL=postgres://postgres@db:5432/postgres
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm run prod'
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ".data-postgres:/var/lib/postgresql/data"
    restart: always