version: "2"
services:
  node:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - db
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=poop
      - DATABASE_URL=postgres://test:test@db:5432/blackford
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm run prod'
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ".data-postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=blackford
    restart: always
  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./dist:/var/lib/assets
      - ./uploads:/var/lib/assets/uploads
    ports:
      - "80:80"
    depends_on:
      - node
    links:
      - node