version: "2"
services:
  node:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://localhost/todos
